// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"novelman/internal/handler"
	"novelman/internal/repository"
	"novelman/internal/server"
	"novelman/internal/service"
	"novelman/pkg/app"
	"novelman/pkg/jwt"
	"novelman/pkg/log"
	"novelman/pkg/server/http"
	"novelman/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(logger, db, client)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	adminRepository := repository.NewAdminRepository(repositoryRepository)
	adminService := service.NewAdminService(serviceService, adminRepository)
	adminHandler := handler.NewAdminHandler(handlerHandler, adminService)
	appRepository := repository.NewAppRepository(repositoryRepository)
	appService := service.NewAppService(serviceService, appRepository)
	appHandler := handler.NewAppHandler(handlerHandler, appService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, adminHandler, appHandler)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewAdminRepository, repository.NewAppRepository, repository.NewPermissionRepository, repository.NewRoleRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewAdminService, service.NewAppService, service.NewRoleService, service.NewPermissionService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewAdminHandler, handler.NewAppHandler, handler.NewPermissionHandler, handler.NewRoleHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("admin"))
}
